---
title: "Exploratory Figures"
author: "Group 2"
date: "4/15/2022"
output: html_document
---

### Data / Package loading

```{r, message=FALSE, warning=FALSE}
# load relevant packages
library(tidyverse)
library(optimx)
library(caret)
library(MASS)
library(ROCR)

# set a randomization seed
set.seed(735)

# load dataset
load("~/bios735_group2/data/HeartDataDerived.RData")
```

```{r}
### Heart Disease ###
# counts of Heart disease occurrence by sex (use this)
ggplot(data = heart.data, aes(x=factor(Sex), fill = factor(HeartDisease))) + theme_classic() + labs(title = "Heart disease counts by sex", x = "Sex", y = "Number of subjects", fill = "Heart Disease")  + scale_fill_discrete(labels = c("No Heart Disease", "Heart Disease")) + geom_bar(position = "fill") + labs(y = "Proportion")
#ggsave("HeartDisease_Sex.png", width = 8, height = 4)

# counts of Heart disease occurrence by Smoking status
ggplot(data = heart.data, aes(x=factor(Smoking), fill = factor(HeartDisease))) + geom_bar(position = "dodge") + theme_classic() + labs(title = "Heart disease counts by smoking status", x = "Smoking Status", y = "Number of subjects", fill = "Heart Disease")  + scale_fill_discrete(labels = c("No Heart Disease", "Heart Disease"))

# counts of Heart disease occurrence by race
ggplot(data = heart.data, aes(x=factor(Race), fill = factor(HeartDisease))) + geom_bar(position = "dodge") + theme_classic() + labs(title = "Heart disease counts by race", x = "race", y = "Number of subjects", fill = "Heart Disease")  + scale_fill_discrete(labels = c("No Heart Disease", "Heart Disease")) + scale_x_discrete(guide = guide_axis(angle = 45))

# counts of Heart disease occurrence by general health
# facet by sex
ggplot(data = heart.data, aes(x=factor(GenHealth), fill = factor(HeartDisease))) + geom_bar(position = "dodge") + theme_classic() + labs(title = "Heart disease counts by general health category", x = "General Health Category", y = "Number of subjects", fill = "Heart Disease")  + scale_fill_discrete(labels = c("No Heart Disease", "Heart Disease")) + scale_x_discrete(guide = guide_axis(angle = 45)) + scale_x_discrete(labels = c("Poor", "Fair", "Good", "Very good", "Excellent")) + facet_wrap(~Sex) + coord_flip()

# facet by physical activity
ggplot(data = heart.data, aes(x=factor(GenHealth), fill = factor(HeartDisease))) + geom_bar(position = "dodge") + theme_classic() + labs(title = "Heart disease counts by general health category (facet by physical activity)", x = "General Health Category", y = "Number of subjects", fill = "Heart Disease")  + scale_fill_discrete(labels = c("No Heart Disease", "Heart Disease")) + scale_x_discrete(guide = guide_axis(angle = 45)) + scale_x_discrete(labels = c("Poor", "Fair", "Good", "Very good", "Excellent")) + facet_wrap(~PhysicalActivity) + coord_flip()
```

```{r}
### Heart Disease by age ###
# facet by sex (use this)
ggplot(data = heart.data, aes(x=factor(AgeCategory), fill = factor(HeartDisease))) + geom_bar(position = "fill") + theme_classic() + labs(title = "Heart disease counts by age group", x = "age group", y = "Number of subjects", fill = "Heart Disease")  + scale_fill_discrete(labels = c("No Heart Disease", "Heart Disease")) + scale_x_discrete(guide = guide_axis(angle = 45)) + facet_wrap(~Sex) + coord_flip() + labs(y = "Proportion")
#ggsave("HeartDisease_Age_Sex.png", width = 8, height = 4)

# facet by smoking status
ggplot(data = heart.data, aes(x=factor(AgeCategory), fill = factor(HeartDisease))) + geom_bar(position = "dodge") + theme_classic() + labs(title = "Heart disease counts by age group", x = "age group", y = "Number of subjects", fill = "Heart Disease")  + scale_fill_discrete(labels = c("No Heart Disease", "Heart Disease")) + facet_wrap(~Smoking) + coord_flip()

# facet by alcohol status
ggplot(data = heart.data, aes(x=factor(AgeCategory), fill = factor(HeartDisease))) + geom_bar(position = "dodge") + theme_classic() + labs(title = "Heart disease counts by age group", x = "age group", y = "Number of subjects", fill = "Heart Disease")  + scale_fill_discrete(labels = c("No Heart Disease", "Heart Disease")) + facet_wrap(~AlcoholDrinking) + coord_flip()

# facet by stroke status
ggplot(data = heart.data, aes(x=factor(AgeCategory), fill = factor(HeartDisease))) + geom_bar(position = "dodge") + theme_classic() + labs(title = "Heart disease counts by age group", x = "age group", y = "Number of subjects", fill = "Heart Disease")  + scale_fill_discrete(labels = c("No Heart Disease", "Heart Disease")) + facet_wrap(~Stroke) + coord_flip()
```

```{r}
### BMI ###
# distribution of BMI values by HeartDisease status
ggplot(data = heart.data, aes(x=BMI, fill = factor(HeartDisease))) + geom_density(alpha = 0.75) + theme_classic() + labs(title = "Distribution of BMI by Heart Disease Status", fill = "Heart Disease")

# distribution of BMI values by Age Category
ggplot(data = heart.data, aes(x=BMI, fill = factor(AgeCategory))) + geom_density(alpha = 0.75) + theme_classic() + labs(title = "Distribution of BMI by Age Category", fill = "Age Category")

# distribution of BMI values by Stroke status
ggplot(data = heart.data, aes(x=BMI, fill = factor(Stroke))) + geom_density(alpha = 0.75) + theme_classic() + labs(title = "Distribution of BMI by Stroke Status", fill = "Stroke")

# box plot of BMI by heart disease status (use this)
ggplot(data = heart.data, aes(x = factor(HeartDisease), y = BMI, fill = factor(HeartDisease))) + geom_boxplot() + theme_classic() + labs(title = "Distribution of BMI by Heart Disease Status", x = "Heart Disease Status", fill = "Heart Disease")
#ggsave("HeartDisease_BMI.png", width = 8, height = 4)

# box plot of BMI by physical activity status
ggplot(data = heart.data, aes(x = factor(PhysicalActivity), y = BMI, fill = factor(PhysicalActivity))) + geom_boxplot() + theme_classic() + labs(title = "Distribution of BMI by Physical Activity Status", x = "Physical Activity Status", fill = "Physical Activity")

# box plot of BMI by age group
ggplot(data = heart.data, aes(x = factor(AgeCategory), y = BMI, fill = factor(AgeCategory))) + geom_boxplot() + theme_classic() + labs(title = "Distribution of BMI by Age Category", x = "Age Category", fill = "Age Category") + scale_x_discrete(guide = guide_axis(angle = 45))
```

```{r, message=FALSE}
### heart disease proportion by: ###
# age
ggplot(data = heart.data, aes(x = AgeCategory, fill = HeartDisease)) + geom_bar(position = "fill") + labs(y = "Proportion") + scale_x_discrete(guide = guide_axis(angle = 45)) + theme_classic()

# sex
ggplot(data = heart.data, aes(x = Sex, fill = HeartDisease)) + geom_bar(position = "fill") + labs(y = "Proportion") + scale_x_discrete(guide = guide_axis(angle = 45)) + theme_classic()

# race
ggplot(data = heart.data, aes(x = Race, fill = HeartDisease)) + geom_bar(position = "fill") + labs(y = "Proportion") + scale_x_discrete(guide = guide_axis(angle = 45)) + theme_classic()

# general health
ggplot(data = heart.data, aes(x = GenHealth, fill = HeartDisease)) + geom_bar(position = "fill") + labs(y = "Proportion") + scale_x_discrete(guide = guide_axis(angle = 45)) + theme_classic() + scale_x_discrete(labels = c("Poor", "Fair", "Good", "Very good", "Excellent"))

## Use these two figures side by side
# smoking
p1 <- ggplot(data = heart.data, aes(x = Smoking, fill = HeartDisease)) + geom_bar(position = "fill") + labs(y = "Proportion") + scale_x_discrete(guide = guide_axis(angle = 45)) + theme_classic()

# alcohol
p2 <- ggplot(data = heart.data, aes(x = AlcoholDrinking, fill = HeartDisease)) + geom_bar(position = "fill") + labs(y = "Proportion") + scale_x_discrete(guide = guide_axis(angle = 45)) + theme_classic()

library(patchwork)
p1+p2
#ggsave("HeartDisease_Smoke_Drink.png", width = 8, height = 4)

# difficulty walking
ggplot(data = heart.data, aes(x = DiffWalking, fill = HeartDisease)) + geom_bar(position = "fill") + labs(y = "Proportion") + scale_x_discrete(guide = guide_axis(angle = 45)) + theme_classic()

# Diabetic
ggplot(data = heart.data, aes(x = Diabetic, fill = HeartDisease)) + geom_bar(position = "fill") + labs(y = "Proportion") + scale_x_discrete(guide = guide_axis(angle = 45)) + theme_classic()

# Physical activity
ggplot(data = heart.data, aes(x = PhysicalActivity, fill = HeartDisease)) + geom_bar(position = "fill") + labs(y = "Proportion") + scale_x_discrete(guide = guide_axis(angle = 45)) + theme_classic()

# Asthma
ggplot(data = heart.data, aes(x = Asthma, fill = HeartDisease)) + geom_bar(position = "fill") + labs(y = "Proportion") + scale_x_discrete(guide = guide_axis(angle = 45)) + theme_classic()

# Kidney Disease
ggplot(data = heart.data, aes(x = KidneyDisease, fill = HeartDisease)) + geom_bar(position = "fill") + labs(y = "Proportion") + scale_x_discrete(guide = guide_axis(angle = 45)) + theme_classic()

# Skin cancer
ggplot(data = heart.data, aes(x = SkinCancer, fill = HeartDisease)) + geom_bar(position = "fill") + labs(y = "Proportion") + scale_x_discrete(guide = guide_axis(angle = 45)) + theme_classic()

# age (facet by physical activity)
ggplot(data = heart.data, aes(x = AgeCategory, fill = HeartDisease)) + geom_bar(position = "fill") + labs(y = "Proportion") + scale_x_discrete(guide = guide_axis(angle = 45)) + theme_classic() + facet_wrap(~PhysicalActivity)

# age (facet by smoking)
ggplot(data = heart.data, aes(x = AgeCategory, fill = HeartDisease)) + geom_bar(position = "fill") + labs(y = "Proportion") + scale_x_discrete(guide = guide_axis(angle = 45)) + theme_classic() + facet_wrap(~Smoking)

# age (facet by Stroke)
ggplot(data = heart.data, aes(x = AgeCategory, fill = HeartDisease)) + geom_bar(position = "fill") + labs(y = "Proportion") + scale_x_discrete(guide = guide_axis(angle = 45)) + theme_classic() + facet_wrap(~Stroke)

# age (facet by diabetes) (use this)
ggplot(data = heart.data, aes(x = AgeCategory, fill = HeartDisease)) + geom_bar(position = "fill") + labs(y = "Proportion") + scale_x_discrete(guide = guide_axis(angle = 45)) + theme_classic() + facet_wrap(~Diabetic) + labs(title = "Heart disease by age and diabetes status", x = "Age Category", fill = "Heart Disease")
#ggsave("HeartDisease_Age_Diabetes.png", width = 8, height = 4)

# age (facet by sex)
ggplot(data = heart.data, aes(x = AgeCategory, fill = HeartDisease)) + geom_bar(position = "fill") + labs(y = "Proportion") + scale_x_discrete(guide = guide_axis(angle = 45)) + theme_classic() + facet_wrap(~Sex)
```

### Relative proportion calcs

```{r}
# heart disease by sex
heart.data %>%
  group_by(Sex, HeartDisease) %>%
  summarise(n = n()) %>%
  mutate(freq = n / sum(n))
```

```{r}
# heart disease by sex & age group
heart.data %>%
  group_by(Sex, HeartDisease, AgeCategory) %>%
  summarise(n = n()) %>%
  mutate(freq = n / sum(n))

heart.data %>%
  group_by(HeartDisease, AgeCategory) %>%
  summarise(n = n()) %>%
  mutate(freq = n / sum(n))

table(heart.data[heart.data$AgeCategory=="80 or older",]$HeartDisease)
```

```{r}
# heart disease by smoking
heart.data %>%
  group_by(Smoking, HeartDisease) %>%
  summarise(n = n()) %>%
  mutate(freq = n / sum(n))

# heart disease by drinking
heart.data %>%
  group_by(AlcoholDrinking, HeartDisease) %>%
  summarise(n = n()) %>%
  mutate(freq = n / sum(n))

# heart disease by diabetes
heart.data %>%
  group_by(Diabetic, HeartDisease) %>%
  summarise(n = n()) %>%
  mutate(freq = n / sum(n))
```

```{r}
#BMI summary stats
favstats(heart.data[heart.data$HeartDisease =="Yes",]$BMI)

favstats(heart.data[heart.data$HeartDisease =="No",]$BMI)

```

