# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

d1_logli <- function(X, y, beta) {
    .Call('_glmLogistic_d1_logli', PACKAGE = 'glmLogistic', X, y, beta)
}

logli <- function(X, Y, beta) {
    .Call('_glmLogistic_logli', PACKAGE = 'glmLogistic', X, Y, beta)
}

beta_updater <- function(X, Y, beta) {
    .Call('_glmLogistic_beta_updater', PACKAGE = 'glmLogistic', X, Y, beta)
}

optim_irls <- function(X, Y, beta, tol = 10^-10, maxit = 50) {
    .Call('_glmLogistic_optim_irls', PACKAGE = 'glmLogistic', X, Y, beta, tol, maxit)
}

optim_BFGS <- function(X, Y, beta, tol = 10^-5, maxit = 10000) {
    .Call('_glmLogistic_optim_BFGS', PACKAGE = 'glmLogistic', X, Y, beta, tol, maxit)
}

