---
title: "GLM - Logistic Regression"
author: "Group 2 - Andrew Walther"
date: "4/13/2022"
output: html_document
---

### Preliminaries - packages/data/preprocessing/test & train sets

```{r, message=FALSE,warning=FALSE}
# load relevant packages
library(tidyverse)
library(optimx)
library(caret)
library(MASS)
library(ROCR)

# save environment as R object
#save.image(file = "HeartDataDerived.RData")
load("~/bios735_group2/data/HeartDataDerived.RData")
```

### Model 1 - all covariates

```{r}
### Model 1 ###
# fit logistic regression model on heart.train (all covariates)
start <- Sys.time()
model.logit.1 <- glm(HeartDisease ~ ., family = "binomial", data = heart.train)
end <- Sys.time()
(time.elapsed <- end-start)

# print logistic regression model parameters
summary(model.logit.1)

# make model predictions (probabilities)
model.1.preds <- predict(model.logit.1, newdata = heart.test, type='response')

# assign binary classification to probabilities
model.1.preds.binary <- ifelse(model.1.preds > 0.5, "Yes", "No")

# compute mis-classification error & print
misClasificError <- mean(model.1.preds.binary != heart.test$HeartDisease)
print(paste('Accuracy',round(1-misClasificError,5)))

# compute confusion matrix for predicted vs. actual (heart disease)
confusionMatrix(as.factor(model.1.preds.binary), as.factor(heart.test$HeartDisease), positive = "Yes")

# table of predicted/observed proportions
tab1 <- table(obs = as.factor(heart.test$HeartDisease), pred = as.factor(model.1.preds.binary))
round(prop.table(tab1),2)

# generated ROC plot
pr <- prediction(model.1.preds, heart.test$HeartDisease)
prf <- performance(pr, measure = "tpr", x.measure = "fpr")
plot(prf)
auc <- performance(pr, measure = "auc")
auc <- auc@y.values[[1]]
print(paste('AUC value:',round(auc,5)))
```

### Model 2 - BMI as lone covariate

```{r}
### Model 2 ###
# fit logistic regression model on heart.train (covariate: BMI)
start <- Sys.time()
model.logit.2 <- glm(HeartDisease ~ BMI, family = "binomial", data = heart.train)
end <- Sys.time()
(time.elapsed <- end-start)

# print logistic regression model parameters
summary(model.logit.2)

# make model predictions (probabilities)
model.2.preds <- predict(model.logit.2, newdata = heart.test, type='response')

# assign binary classification to probabilities
model.2.preds.binary <- ifelse(model.2.preds > 0.5, "Yes", "No")

# compute misclassification error & print
misClasificError <- mean(model.2.preds.binary != heart.test$HeartDisease)
print(paste('Accuracy',round(1-misClasificError,5)))

# compute confusion matrix for predicted vs. actual (heart disease)
confusionMatrix(as.factor(model.2.preds.binary), as.factor(heart.test$HeartDisease), positive = "Yes")

# table of predicted/observed proportions
tab2 <- table(obs = as.factor(heart.test$HeartDisease), pred = as.factor(model.2.preds.binary))
round(prop.table(tab2),2)

# generated ROC plot
pr <- prediction(model.2.preds, heart.test$HeartDisease)
prf <- performance(pr, measure = "tpr", x.measure = "fpr")
plot(prf)
auc <- performance(pr, measure = "auc")
auc <- auc@y.values[[1]]
print(paste('AUC value:',round(auc,5)))
```

### Model 3 - Smoking & Alcohol Drinking for Heart Disease

```{r}
### Model 3 ###
# fit logistic regression model on heart.train (covariate: Smoking + AlcoholDrinking)
start <- Sys.time()
model.logit.3 <- glm(HeartDisease ~ Smoking*AlcoholDrinking, family = "binomial", data = heart.train)
end <- Sys.time()
(time.elapsed <- end-start)

# print logistic regression model parameters
summary(model.logit.3)

# make model predictions (probabilities)
model.3.preds <- predict(model.logit.3, newdata = heart.test, type='response')

# assign binary classification to probabilities
model.3.preds.binary <- ifelse(model.3.preds > 0.5, "Yes", "No")

# compute misclassification error & print
misClasificError <- mean(model.2.preds.binary != heart.test$HeartDisease)
print(paste('Accuracy',round(1-misClasificError,5)))

# compute confusion matrix for predicted vs. actual (heart disease)
confusionMatrix(as.factor(model.3.preds.binary), as.factor(heart.test$HeartDisease), positive = "Yes")

# table of predicted/observed proportions
tab3 <- table(obs = as.factor(heart.test$HeartDisease), pred = as.factor(model.3.preds.binary))
round(prop.table(tab3),2)

# generated ROC plot
pr <- prediction(model.3.preds, heart.test$HeartDisease)
prf <- performance(pr, measure = "tpr", x.measure = "fpr")
plot(prf)
auc <- performance(pr, measure = "auc")
auc <- auc@y.values[[1]]
print(paste('AUC value:',round(auc,5)))
```

### Model 4 - Smoking & Alcohol Drinking for Stroke

```{r}
### Model 4 ###
# fit logistic regression model on heart.train (covariate: Smoking + AlcoholDrinking)
start <- Sys.time()
model.logit.4 <- glm(Stroke ~ Smoking*AlcoholDrinking, family = "binomial", data = heart.train)
end <- Sys.time()
(time.elapsed <- end-start)

# print logistic regression model parameters
summary(model.logit.4)

# make model predictions (probabilities)
model.4.preds <- predict(model.logit.4, newdata = heart.test, type='response')

# assign binary classification to probabilities
model.4.preds.binary <- ifelse(model.4.preds > 0.5, "Yes", "No")

# compute misclassification error & print
misClasificError <- mean(model.4.preds.binary != heart.test$HeartDisease)
print(paste('Accuracy',round(1-misClasificError,5)))

# compute confusion matrix for predicted vs. actual (heart disease)
confusionMatrix(as.factor(model.4.preds.binary), as.factor(heart.test$HeartDisease), positive = "Yes")

# table of predicted/observed proportions
tab4 <- table(obs = as.factor(heart.test$HeartDisease), pred = as.factor(model.4.preds.binary))
round(prop.table(tab4),2)

# generated ROC plot
pr <- prediction(model.4.preds, heart.test$HeartDisease)
prf <- performance(pr, measure = "tpr", x.measure = "fpr")
plot(prf)
auc <- performance(pr, measure = "auc")
auc <- auc@y.values[[1]]
print(paste('AUC value:',round(auc,5)))
```

### Model 5 - Indicators of "good health"

```{r}
### Model 5 ###
# fit logistic regression model on heart.train (covariate: Smoking + AlcoholDrinking)
start <- Sys.time()
model.logit.5 <- glm(HeartDisease ~ PhysicalHealth + MentalHealth + PhysicalActivity + GenHealth + SleepTime + AgeCategory + Sex, family = "binomial", data = heart.train)
end <- Sys.time()
(time.elapsed <- end-start)

# print logistic regression model parameters
summary(model.logit.5)

# make model predictions (probabilities)
model.5.preds <- predict(model.logit.5, newdata = heart.test, type='response')

# assign binary classification to probabilities
model.5.preds.binary <- ifelse(model.5.preds > 0.5, "Yes", "No")

# compute misclassification error & print
misClasificError <- mean(model.5.preds.binary != heart.test$HeartDisease)
print(paste('Accuracy',round(1-misClasificError,5)))

# compute confusion matrix for predicted vs. actual (heart disease)
confusionMatrix(as.factor(model.5.preds.binary), as.factor(heart.test$HeartDisease), positive = "Yes")

# table of predicted/observed proportions
tab5 <- table(obs = as.factor(heart.test$HeartDisease), pred = as.factor(model.5.preds.binary))
round(prop.table(tab5),2)

# generated ROC plot
pr <- prediction(model.5.preds, heart.test$HeartDisease)
prf <- performance(pr, measure = "tpr", x.measure = "fpr")
plot(prf)
auc <- performance(pr, measure = "auc")
auc <- auc@y.values[[1]]
print(paste('AUC value:',round(auc,5)))
```

### Model 6 - Stepwise variable selection

```{r}
# fit logistic regression model on heart.train (all covariates)
start <- Sys.time()
model.logit.full <- glm(HeartDisease ~ ., family = "binomial", data = heart.train)
model.logit.step <- model.logit.full %>% stepAIC(trace = FALSE)
coef(model.logit.step)
end <- Sys.time()
(time.elapsed <- end-start)

# print logistic regression model parameters
summary(model.logit.step)

# make model predictions (probabilities)
model.step.preds <- predict(model.logit.step, newdata = heart.test, type='response')

# assign binary classification to probabilities
model.step.preds.binary <- ifelse(model.step.preds > 0.5, "Yes", "No")

# compute misclassification error & print
misClasificError <- mean(model.step.preds.binary != heart.test$HeartDisease)
print(paste('Accuracy',round(1-misClasificError,5)))

# compute confusion matrix for predicted vs. actual (heart disease)
confusionMatrix(as.factor(model.step.preds.binary), as.factor(heart.test$HeartDisease), positive = "Yes")

# table of predicted/observed proportions
tab.step <- table(obs = as.factor(heart.test$HeartDisease), pred = as.factor(model.step.preds.binary))
round(prop.table(tab.step),2)

# generated ROC plot
pr <- prediction(model.step.preds, heart.test$HeartDisease)
prf <- performance(pr, measure = "tpr", x.measure = "fpr")
plot(prf)
auc <- performance(pr, measure = "auc")
auc <- auc@y.values[[1]]
print(paste('AUC value:',round(auc,5)))
```

```{r}
# fit logistic regression model on heart.train (backward selection)
start <- Sys.time()
model.logit.full <- glm(HeartDisease ~ ., family = "binomial", data = heart.train)
model.logit.step <- step(model.logit.full, trace = 0)
coef(model.logit.step)
formula(model.logit.step)
end <- Sys.time()
(time.elapsed <- end-start)

# print logistic regression model parameters
summary(model.logit.step)

# make model predictions (probabilities)
model.step.preds <- predict(model.logit.step, newdata = heart.test, type='response')

# assign binary classification to probabilities
model.step.preds.binary <- ifelse(model.step.preds > 0.5, "Yes", "No")

# compute misclassification error & print
misClasificError <- mean(model.step.preds.binary != heart.test$HeartDisease)
print(paste('Accuracy',round(1-misClasificError,5)))

# compute confusion matrix for predicted vs. actual (heart disease)
confusionMatrix(as.factor(model.step.preds.binary), as.factor(heart.test$HeartDisease), positive = "Yes")

# table of predicted/observed proportions
tab.step <- table(obs = as.factor(heart.test$HeartDisease), pred = as.factor(model.step.preds.binary))
round(prop.table(tab.step),2)

# generated ROC plot
pr <- prediction(model.step.preds, heart.test$HeartDisease)
prf <- performance(pr, measure = "tpr", x.measure = "fpr")
plot(prf)
auc <- performance(pr, measure = "auc")
auc <- auc@y.values[[1]]
print(paste('AUC value:',round(auc,5)))
```

```{r}
# fit logistic regression model on heart.train (forward selection)
start <- Sys.time()
model.logit.null <- glm(HeartDisease ~ 1, family = "binomial", data = heart.train)
model.logit.step <- step(model.logit.null, trace = 0, direction = "forward")
coef(model.logit.step)
formula(model.logit.step)
end <- Sys.time()
(time.elapsed <- end-start)

# print logistic regression model parameters
summary(model.logit.step)

# make model predictions (probabilities)
model.step.preds <- predict(model.logit.step, newdata = heart.test, type='response')

# assign binary classification to probabilities
model.step.preds.binary <- ifelse(model.step.preds > 0.5, "Yes", "No")

# compute misclassification error & print
misClasificError <- mean(model.step.preds.binary != heart.test$HeartDisease)
print(paste('Accuracy',round(1-misClasificError,5)))

# compute confusion matrix for predicted vs. actual (heart disease)
confusionMatrix(as.factor(model.step.preds.binary), as.factor(heart.test$HeartDisease), positive = "Yes")

# table of predicted/observed proportions
tab.step <- table(obs = as.factor(heart.test$HeartDisease), pred = as.factor(model.step.preds.binary))
round(prop.table(tab.step),2)

# generated ROC plot
pr <- prediction(model.step.preds, heart.test$HeartDisease)
prf <- performance(pr, measure = "tpr", x.measure = "fpr")
plot(prf)
auc <- performance(pr, measure = "auc")
auc <- auc@y.values[[1]]
print(paste('AUC value:',round(auc,5)))
```

```{r}
# fit logistic regression model on heart.train (forward & backward selection)
start <- Sys.time()
model.logit.null <- glm(HeartDisease ~ 1, family = "binomial", data = heart.train)
model.logit.full <- glm(HeartDisease ~ ., family = "binomial", data = heart.train)
model.logit.step <- step(model.logit.null, list(lower=formula(model.logit.null), upper = formula(model.logit.full)), trace = 0, direction = "both")
coef(model.logit.step)
formula(model.logit.step)
end <- Sys.time()
(time.elapsed <- end-start)

# print logistic regression model parameters
summary(model.logit.step)

# make model predictions (probabilities)
model.step.preds <- predict(model.logit.step, newdata = heart.test, type='response')

# assign binary classification to probabilities
model.step.preds.binary <- ifelse(model.step.preds > 0.5, "Yes", "No")

# compute misclassification error & print
misClasificError <- mean(model.step.preds.binary != heart.test$HeartDisease)
print(paste('Accuracy',round(1-misClasificError,5)))

# compute confusion matrix for predicted vs. actual (heart disease)
confusionMatrix(as.factor(model.step.preds.binary), as.factor(heart.test$HeartDisease), positive = "Yes")

# table of predicted/observed proportions
tab.step <- table(obs = as.factor(heart.test$HeartDisease), pred = as.factor(model.step.preds.binary))
round(prop.table(tab.step),2)

# generated ROC plot
pr <- prediction(model.step.preds, heart.test$HeartDisease)
prf <- performance(pr, measure = "tpr", x.measure = "fpr")
plot(prf)
auc <- performance(pr, measure = "auc")
auc <- auc@y.values[[1]]
print(paste('AUC value:',round(auc,5)))
```